### ISSUE TITLE
Call to undefined function curl_init()

### ISSUE THREAD

**Issue by qkqpttgf** [vercel-community/php#571]
# Bug report

- Version: 0.7.2
- URL:  No
- Repository:  No

## Description
Fatal error: Uncaught Error: Call to undefined function curl_init()
----
I am sorry but the 0.7.2 version do not contain the curl model.
Can you fix that? or how can I do with it myself?

**Comment by f3l1x** [comment]
Hi, thank you for report. Going to investigate ASAP.

**Comment by DiegoRomeroSalcedo** [comment]
Hola, yo use lo que es la versión vercel-php@0.7.2, para hacer get, pues use file_get_content, pero pues para APIS que requieren protocolos como lo son POST, PUT, DELETE, si seria bueno que cURL, este activo, puesto que si sería demasiado util.

**Comment by f3l1x** [comment]
Hi, it should be fixed. Please try version `0.7.3.` :-)

**Comment by qkqpttgf** [comment]
> Hi, it should be fixed. Please try version `0.7.3.` :-)

it works!

**Comment by DiegoRomeroSalcedo** [comment]
Hello, qkqpttgf, I started with this project yesterday, but I have a question, since although I use version 2, and I also implement static files, it generates the same error, how did you implement it, I would appreciate your response:

{
  "version": 2,
  "builds": [
    { "src": "api/index.php", "use": "vercel-php@0.7.3" },
    { "src": "public/**", "use": "@vercel/static" }
  ],
  "routes": [
    { "src": "/css/(.*)", "dest": "/public/css/$1" },
    { "src": "/(.*)", "dest": "/api/index.php" }
  ]
}

**Comment by DiegoRomeroSalcedo** [comment]
Hello, I'm trying to download the changes from the repository, installing the vercel CLI again and doing the deployment, the php info tells me that I have php version 8.3.8, but I'm trying to run curl_init() for a simple api in which I only You can make GET protocols, but nothing, it still doesn't work for me, your implementation requires some additional detail, my vercel.json looks like this:
{
  "version": 2,
  "build": [
    { "src": "api/index.php", "usage": "vercel-php@0.7.3" },
    { "src": "public/**", "use": "@vercel/static" }
  ],
  "routes": [
    { "src": "/css/(.*)", "dest": "/public/css/$1" },
    { "src": "/(.*)", "dest": "/api/index.php" }
  ]
}
Sorry for the inconvenience, I just started with this tool, your answer would help me a lot.

**Comment by qkqpttgf** [comment]
> Hello, I'm trying to download the changes from the repository, installing the vercel CLI again and doing the deployment, the php info tells me that I have php version 8.3.8, but I'm trying to run curl_init() for a simple api in which I only You can make GET protocols, but nothing, it still doesn't work for me, your implementation requires some additional detail, my vercel.json looks like this: { "version": 2, "build": [ { "src": "api/index.php", "usage": "vercel-php@0.7.3" }, { "src": "public/**", "use": "@vercel/static" } ], "routes": [ { "src": "/css/(._)", "dest": "/public/css/$1" }, { "src": "/(._)", "dest": "/api/index.php" } ] } Sorry for the inconvenience, I just started with this tool, your answer would help me a lot.

vercel.json file contents something wrong.
you can use my tool to deploy, `https://scfonedrive.github.io/Vercel/Deploy.html` , if there is only 1 index.php in all files,

**Comment by nadar** [comment]
@f3l1x i use `vercel-php@0.7.3` and it seems to miss curl again.

**Comment by nadar** [comment]
#573 issue regarding missing curl
